/Control_Node:
  ros__parameters:
    Buoancy: 10.0
    Weight: 10.0
    Centre_of_buoyancy:
    - 0.0
    - 0.0
    - 0.0
    Centre_of_gravity:
    - 0.0
    - 0.0
    - 0.0
    Proportional_gain_angular: 10.0
    Proportional_gain_linear: 0.0
    Derivative_gain: 1.0
    Control_mode: 1
    Setpoint_input_mode: 0
    World_frame_type: 1
