/Control_Node:
  ros__parameters:
    Buoancy: 10.0                         # Upwards forces from buoancy
    Weight: 10.0                          # Downwards forces from weight
    Centre_of_buoyancy:                   # Geometrical centre of buoyancy
    - 0.0 # x
    - 0.0 # y
    - 0.0 # z
    Centre_of_gravity:                    # Geometrical centre of gravity
    - 0.0 # x
    - 0.0 # y
    - 0.0 # z
    Proportional_gain_angular: 20.0       # Proportional gain used in angular control
    Proportional_gain_linear: 0.0         # Proportional gain used in linear control
    Integral_gain_angular: 2.0            # Integral gain used in angular control
    Integral_gain_linear: 0.0             # Integral gain used in linear control
    Derivative_gain: 5.0                  # Derivative gain used in angular and linear control
    Integral_windup_linear: 4.0           # Maximum integral windup linear
    Integral_windup_angular: 4.0          # Maximum integral windup angular
    Control_mode: 1                       # Type of control mode. 0 = manual, 1 = controller, 2 = depth hold
    Use_integrator: false                 # Boolean to decide if integrator should be connected (WARNING: STABILITY NOT GUARANTEED. USE AT OWN RISK)
    Use_param_file_setpoint: true        # Use parameter file setpoints
    World_frame_type: 0                   # Compensate joystick input for different body frames
    Use_imu_directly: false               # Use data from IMU directly instead of state estimate