/Control_Node:
  ros__parameters:
    Buoancy_and_Weight: 8.0
    Centre_of_buoyancy:
    - 0.0
    - 0.0
    - 0.0
    Centre_of_gravity:
    - 0.0
    - 0.0
    - 0.0
    Derivative_gain: 1.0
    G_force: 10.0
    Proportional_gain_angular: 20.0
    Proportional_gain_linear: 2.0
    Integral_gain_angular: 0.0
    Integral_gain_linear: 0.0
    Windup_max_attitude: 1.0
    Windup_max_position: 5.0
    Scaling_heave: 1.0
    Scaling_surge: 1.0
    Scaling_sway: 1.0
    Control_mode: 1
    Input_mode: 1
    World_frame_type: 1
    Attitude_setpoint:
    - 0.0023
    - 0.063
    - 0.997
    - 0.022
    Position_setpoint:
    - 0.0
    - 0.0
    - 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

