/Control_Node:
  ros__parameters:
    #Physical properties
    Buoancy: 10.0                         # Upwards forces from buoancy
    Weight: 30.0                          # Downwards forces from weight
    Centre_of_buoyancy:                   # Geometrical centre of buoyancy
    - 0.0 # x
    - 0.0 # y
    - 0.0 # z
    Centre_of_gravity:                    # Geometrical centre of gravity
    - 0.0 # x
    - 0.0 # y
    - 0.0 # z

    #Controller gain: proportional
    Proportional_gain_angular: 20.0       # Proportional gain used in angular control
    Proportional_gain_linear: 40.0        # Proportional gain used in linear control

    #Controller gain: integrator
    Integral_gain_angular: 2.0            # Integral gain used in angular control
    Integral_gain_linear: 0.0             # Integral gain used in linear control
    Integral_windup_linear: 4.0           # Maximum integral windup linear
    Integral_windup_angular: 4.0          # Maximum integral windup angular

    #Controller gain: derivation
    Derivative_gain: 5.0                  # Derivative gain used in angular and linear control

    #Controller settings
    Enable_integrator: false              # Boolean to decide if integrator should be connected (WARNING: STABILITY NOT GUARANTEED. USE AT OWN RISK)
    Linear_control_xy: false              # Enable/Disable positional control in the xy-plane
    Linear_control_z: false               # Enable/Disable positional control on the z - axis
    Load_setpoint_from_topic: false       # Use setpoint from ROS2 topic
    Enable_controller: false              # Enable/disable control system

    #Teleoperation settings
    Compensate_NED: true                  # If body frame is in NED, this makes manual control more intuitive
    Manual_control_scaling: 40.0          # Scale manual control sensitivity
